name: Run Cypress with param

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Code to pass to Cypress'
        required: true
        default: 'ABC123'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress with param
        run: |
          echo "Code param: ${{ github.event.inputs.code }}"
          npx cypress run --env testCode=${{ github.event.inputs.code }}
