name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Code à tester (sera injecté dans les variables d’environnement)'
        required: true
        default: 'default-code'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        env:
          CYPRESS_TEST_ID_INTER: ${{ github.event.inputs.code }}
        run: |
          echo "Code reçu : $CYPRESS_TEST_ID_INTER"
          npx cypress run --spec "cypress/e2e/UseCaseAgentRespRobot.cy.ts"
